package com.springboot.constant;

/**
 * 传输协议常量枚举类
 * @author mrliz
 */

public enum TransferAgreement {
    /**
     *
     */
    PACKAGE_TYPE_CLIENT_REGISTER((short) 0),

    /**
     *
     */
    PACKAGE_TYPE_CLIENT_REGISTER_ACK((short) 1),

    /**
     *
     */
    PACKAGE_TYPE_UPLOAD_FILE((short)2),

    PACKAGE_TYPE_UPLOAD_FILE_ACK((short)3),

    PACKAGE_TYPE_UPLOAD_BLOCK_FILE((short)4),

    PACKAGE_TYPE_UPLOAD_BLOCK_FILE_ACK((short)5),
    PACKAGE_TYPE_UPLOAD_BLOCK_DATA((short)6),
    PACKAGE_TYPE_UPLOAD_BLOCK_DATA_ACK_SUCCESS((short)7),
    PACKAGE_TYPE_UPLOAD_BLOCK_DATA_ACK_RESEND((short)8),
    PACKAGE_TYPE_UPLOAD_BLOCK_FILE_FINISH((short)9),
    PACKAGE_TYPE_UPLOAD_BLOCK_FILE_FINISH_ACK_SUCCESS((short)10),
    PACKAGE_TYPE_UPLOAD_BLOCK_FILE_FINISH_ACK_RESEND((short)11),
    PACKAGE_TYPE_UPLOAD_FILE_FINISH((short)12),
    PACKAGE_TYPE_UPLOAD_FILE_FINISH_ACK_SUCCESS((short)13),
    PACKAGE_TYPE_UPLOAD_FILE_FINISH_ACK_RESEND((short)14),
    PACKAGE_TYPE_DOWNLOAD_REQUEST((short)15),
    PACKAGE_TYPE_DOWNLOAD_REQUEST_ACK_NO_FILE((short)16),
    PACKAGE_TYPE_DOWNLOAD_REQUEST_ACK_FILE_INFO((short)17),
    PACKAGE_TYPE_DOWNLOAD_CONTENT_REQUEST((short)18),
    PACKAGE_TYPE_DOWNLOAD_CONTENT_REQUEST_ACK((short)19),
    PACKAGE_TYPE_DOWNLOAD_FINISH((short)20),
    PACKAGE_TYPE_DOWNLOAD_FINISH_ACK_SIZE_CHANGE((short)21),
    PACKAGE_TYPE_DOWNLOAD_FINISH_ACK_SUCCESS((short)22),
    PACKAGE_TYPE_DOWNLOAD_CHECK_MD5((short)23),
    PACKAGE_TYPE_DOWNLOAD_CHECK_MD5_ACK((short)24),
    PACKAGE_TYPE_CLIENT_HEARTBEAT_SYNC((short)25),
    PACKAGE_TYPE_CLIENT_HEARTBEAT_SYNC_ACK((short)26),
    PACKAGE_TYPE_CLIENT_CONFIG_SYNC((short)27),
    PACKAGE_TYPE_CLIENT_BUSSINESS_CONFIG_SYNC((short)28),
    PACKAGE_TYPE_CLIENT_CONFIG((short)29),
    PACKAGE_TYPE_CLIENT_BUSSINESS_CONFIG((short)30),
    PACKAGE_TYPE_CLIENT_CONFIG_ACK((short)31),
    PACKAGE_TYPE_CLIENT_BUSSINESS_CONFIG_ACK((short)32),
    PACKAGE_TYPE_UPLOAD_CANCEL((short)33),
    PACKAGE_TYPE_UPLOAD_CANCEL_ACK((short)34);


    private final short value;

    TransferAgreement(short value) {
        this.value = value;
    }

    public short getValue() {
        return value;
    }
}
